// <auto-generated />
using System;
using ApiFastReport.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiFastReport.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("ApiFastReport.Entity.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 219, DateTimeKind.Utc).AddTicks(8839),
                            Descricao = "Combustivel"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 219, DateTimeKind.Utc).AddTicks(8851),
                            Descricao = "Lubrificantes"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 219, DateTimeKind.Utc).AddTicks(8856),
                            Descricao = "Diversos"
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(5279),
                            Email = "sofia@mail.com",
                            Nome = "Sofia Marli Porto"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(5286),
                            Email = "raimunda@mail.com",
                            Nome = "Raimunda Isis Olivia Vieira"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(5289),
                            Email = "oliver@mail.com",
                            Nome = "Oliver Arthur da Mota"
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Foto")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 217, DateTimeKind.Utc).AddTicks(9336),
                            Email = "postocidade@mail.com",
                            Foto = "",
                            Nome = "Posto de Gasolina Cidade"
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Ean")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1369),
                            Descricao = "Gasolina Aditivada",
                            Ean = "9789563530701",
                            Preco = 5.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1827),
                            Descricao = "Gasolina Comum",
                            Ean = "9789563530702",
                            Preco = 5.10m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1832),
                            Descricao = "Alcool Comum",
                            Ean = "9789563530703",
                            Preco = 4.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1835),
                            Descricao = "Alcool Aditivado",
                            Ean = "9789563530704",
                            Preco = 4.15m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1837),
                            Descricao = "Diesel",
                            Ean = "9789563530705",
                            Preco = 3.98m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1840),
                            Descricao = "Óleo Lubrificante Motor 20w",
                            Ean = "9789563530710",
                            Preco = 20.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1843),
                            Descricao = "Óleo Lubrificante Motor 40w",
                            Ean = "9789563530711",
                            Preco = 21.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1846),
                            Descricao = "Água sem Gás",
                            Ean = "9789563530720",
                            Preco = 2.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(1849),
                            Descricao = "Água com Gás",
                            Ean = "9789563530721",
                            Preco = 2.10m
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3693),
                            Email = "fernandosilva@mail.com",
                            Nome = "Fernando Silva"
                        },
                        new
                        {
                            Id = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3701),
                            Email = "marcos@mail.com",
                            Nome = "Marcos"
                        },
                        new
                        {
                            Id = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3704),
                            Email = "ellena@mail.com",
                            Nome = "Ellena"
                        },
                        new
                        {
                            Id = 4,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3707),
                            Email = "Rafaela@mail.com",
                            Nome = "Rafaela"
                        },
                        new
                        {
                            Id = 5,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3709),
                            Email = "heloisa@mail.com",
                            Nome = "Heloisa"
                        },
                        new
                        {
                            Id = 6,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3712),
                            Email = "manuella@mail.com",
                            Nome = "Manuella"
                        },
                        new
                        {
                            Id = 7,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(3714),
                            Email = "luan@mail.com",
                            Nome = "Luan"
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalVenda")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Vendas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClienteId = 2,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(6931),
                            DataVenda = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(6452),
                            TotalVenda = 100.00m
                        },
                        new
                        {
                            Id = 2,
                            ClienteId = 3,
                            CreateAt = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(7443),
                            DataVenda = new DateTime(2021, 8, 18, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(7439),
                            TotalVenda = 75.00m
                        },
                        new
                        {
                            Id = 3,
                            ClienteId = 1,
                            CreateAt = new DateTime(2021, 8, 20, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(7587),
                            DataVenda = new DateTime(2021, 8, 20, 12, 7, 19, 220, DateTimeKind.Utc).AddTicks(7447),
                            TotalVenda = 200.00m
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.VendaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("TotalProduto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("ValorProduto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("VendaItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProdutoId = 2,
                            Quantidade = 18.18m,
                            TotalProduto = 100.00m,
                            ValorProduto = 5.50m,
                            VendaId = 1
                        },
                        new
                        {
                            Id = 2,
                            ProdutoId = 1,
                            Quantidade = 9.80m,
                            TotalProduto = 50.00m,
                            ValorProduto = 5.10m,
                            VendaId = 2
                        },
                        new
                        {
                            Id = 3,
                            ProdutoId = 9,
                            Quantidade = 12m,
                            TotalProduto = 25.00m,
                            ValorProduto = 2.10m,
                            VendaId = 2
                        },
                        new
                        {
                            Id = 4,
                            ProdutoId = 5,
                            Quantidade = 50.24m,
                            TotalProduto = 200.00m,
                            ValorProduto = 3.98m,
                            VendaId = 3
                        });
                });

            modelBuilder.Entity("ApiFastReport.Entity.Produto", b =>
                {
                    b.HasOne("ApiFastReport.Entity.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ApiFastReport.Entity.Venda", b =>
                {
                    b.HasOne("ApiFastReport.Entity.Cliente", "Cliente")
                        .WithMany("Vendas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ApiFastReport.Entity.VendaItem", b =>
                {
                    b.HasOne("ApiFastReport.Entity.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiFastReport.Entity.Venda", "Venda")
                        .WithMany("VendaItens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("ApiFastReport.Entity.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("ApiFastReport.Entity.Cliente", b =>
                {
                    b.Navigation("Vendas");
                });

            modelBuilder.Entity("ApiFastReport.Entity.Venda", b =>
                {
                    b.Navigation("VendaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
